# Generated by Django 4.2.5 on 2023-10-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('phonenumber', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'register',
            },
        ),
    ]
