# Generated by Django 4.2.5 on 2023-10-06 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='phonenumber',
            new_name='email',
        ),
    ]
